### PR TITLE
rruleset & rrulestr

### PR DESCRIPTION
**Pull request by island205**

### CODE REVIEW

**Comment by island205** [comment]
wait for me to fix some issues

**Comment by jakubroztocil** [comment]
:+1:

**Comment by island205** [comment]
@jakubroztocil fixed, please have a look!

**Comment by mvallerie** [comment]
:+1:  for this. Having rruleset and rrulestr would be really awesome :).

**Comment by island205** [comment]
any update for this PR?

**Comment by zensh** [comment]
RRuleSet works now!

**Comment by jkbrzt** [comment]
@island205 @zensh  This is great, thanks!  

It's a big change I and don't have time to make a detailed review. Could you please provide some additional Information, like:

* Is it a port of the Python implementation?
* If yes, is the API identical?
* etc.

Also, please document the new functionality in the README.

**Comment by zensh** [comment]
@jkbrzt I added some document. It is a part of the Python implementation, API is identical. :1234:

**Comment by jkbrzt** [comment]
@zensh Thanks! :+1: :+1: :+1:

**Pull request merged**
